### ISSUE TITLE
fix upon pull request is not working

### ISSUE THREAD

**Issue by cilerler** [xt0rted/dotnet-format#10]
As you may see [here](https://github.com/cilerler/orange/blob/cilerler-patch-1/.github/workflows/pull_request.yml), I tried to make pull requests as fixer action. 

Two issues occurred,

1. It triggered a new action upon commit
2. `steps.format.outputs.has-changes` returns `true` even there is no file to commit, which causes an additional error you may find it in [here](https://github.com/cilerler/orange/runs/499223128?check_suite_focus=true)

I don't want to use a comment; if the formatting is wrong, it should be fixed it right at the commit into the pull request in my case.

**Comment by xt0rted** [comment]
Hi @cilerler, the link to your workflow file is giving me a 404 error. Could you include a copy of it here in the issue for me to see?

**Comment by cilerler** [comment]
Hi, @xt0rted,

my bad, I just switched it to a public repository, please let me know if you will still have any issue to access it.

**Comment by xt0rted** [comment]
There's a few things going on here.

1. You don't need to use `xt0rted/pull-request-comment-branch` with the `pull_request` event. Instead you can use `${{ github.head_ref }}` or `${{ github.event.pull_request.head.ref }}` during checkout and push.

2. Since you don't want the push from this to trigger another build you should use `GITHUB_TOKEN` instead of a Personal Access Token. When using this token `persist-credentials` isn't needed on the checkout step.

3. The extra blank line in the commit message is needed for [co-authored-by](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) to be picked up by GitHub. This part of the commit message is optional, I found it useful to know who caused the commit to be created.

Give this workflow a try. It's working in one of my test repos. I'll add this to the readme as long as it works for you.

```yml
name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet-format
        run: |
          echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
          dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run dotnet format
        id: format
        uses: xt0rted/dotnet-format@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: true

      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m 'Automated dotnet-format update

          Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

      - name: Push changes
        if: steps.format.outputs.has-changes == 'true'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
```
