### ISSUE TITLE
Commit step not finding any changes

### ISSUE THREAD

**Issue by WouterDeKort** [xt0rted/dotnet-format#333]
I am running `dotnet format` and then trying to commit and push the changes. I can see that the format step updates some files but somehow the commit step doesn't find any changes. 

This is the output of the commit step:

```
Running in /home/runner/work/project/project
Add input parsed as single string, running 1 git add command.
> Using 'Github Actions <actions@github.com>' as author.
> Using "Automated dotnet-format update" as commit message.
Internal logs
> Working tree clean. Nothing to commit.
Outputs
```

I don't understand how the working tree can be clear after the `dotnet format` step formatted 4 files.

This is my YAML:

```
name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version "5.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run dotnet format
        id: format
        uses: xt0rted/dotnet-format@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: false
          fail-fast: false
      
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: Automated dotnet-format update

```

Any idea what I'm doing wrong?
