### ISSUE TITLE
Fix on pull request:  nothing to commit, working tree clean

### ISSUE THREAD

**Issue by anthony-steele-cko** [xt0rted/dotnet-format#98]
I am seeing similar to the `nothing to commit, working tree clean` issue here: https://github.com/xt0rted/dotnet-format/issues/10#issuecomment-598464578, and it does not seem to be due to line-ending settings

I made a PR, with the config file similar to given there, and also added extra spaces to a code file, so that the format would have something to fix.
The result is that it is formatetd, folowed by ` `nothing to commit, working tree clean` 

![image](https://user-images.githubusercontent.com/66946391/91967665-6d284400-ed0b-11ea-8bac-ff46bcd4eff1.png)

**Comment by anthony-steele-cko** [comment]
My `format.yml` file is as follows:

```yml
name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        id: format
        uses: xt0rted/dotnet-format@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: true

      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m 'Automated dotnet-format update

          Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

      - name: Push changes
        if: steps.format.outputs.has-changes == 'true'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
```
